### ISSUE TITLE
Density plot mirroring param

### ISSUE THREAD

**Issue by xiaoyingpu** [MUCollective/pgog#43]
Switching between half-eye and violin plots, see http://mjskay.github.io/tidybayes/reference/stat_sample_slabinterval.html

- top/left
- bottom/right
- both

**Comment by xiaoyingpu** [comment]
@citywallum If you're still working on this... some potentially useful links

https://github.com/mjskay/tidybayes/blob/d57f54ee5ec7de2dfb14dc781402604cc8305b20/R/geom_slabinterval.R#L43

https://github.com/mjskay/tidybayes/blob/a49db927e4dbef58c79510dc9805bd18318e3274/R/draw_key_slabinterval.R

https://github.com/tidyverse/ggplot2/blob/master/R/geom-violin.r

**Comment by xiaoyingpu** [comment]
@citywallum Matt thought this function might be useful here https://github.com/mjskay/tidybayes/blob/d57f54ee5ec7de2dfb14dc781402604cc8305b20/R/geom_slabinterval.R#L642

**Comment by citywallum** [comment]
now it is able to plot graphs that centers at y axis successfully, but if the graphs center at different y values, the canvas would only should a part of graphs

**Comment by citywallum** [comment]
looking for code to reset the size of canvas

**Comment by xiaoyingpu** [comment]
> looking for code to reset the size of canvas

Are the tails of the densities look like they're cut off? The function that calculates the densities picks some defaults for how far the tails go and sometimes they do look cut off... just make sure that it's not the density function calculation before you go down other rabbit holes.

**Comment by citywallum** [comment]
The problem is that the window is wrong. I think the all the curves are at their correct position. For example, if i want to plot a "down" graph, all the curves are flipped but the window is still set for plotting those "up" graphs.

**Comment by citywallum** [comment]
ok nvm the window issue is solved
