### ISSUE TITLE
handle fill = factor() correctly in parsing 

### ISSUE THREAD

**Issue by xiaoyingpu** [MUCollective/pgog#82]
Well PR #81 broke this bit

Somewhere around https://github.com/MUCollective/pgog/blame/parser_fixes/R/parse.R#L294

**Comment by mjskay** [comment]
is this a case where if someone is using `factor()` in the spec they should actually be converting the variable ahead of time before running it through ggplot?

**Comment by xiaoyingpu** [comment]
Yeah theoretically but I do stuff like this all the time especially when I need to map factors to colors
```
ggplot(mtcars, aes(x = factor(cyl), y = mpg)) + geom_col()
```

**Comment by mjskay** [comment]
Sure, but a simple rewrite is something like:

```r
mtcars %>%
  mutate(cyl = factor(cyl)) %>%
  ggplot(aes(x = cyl, y = mpg, fill = cyl) +
  geom_col()
```

Then you only have to do the conversion once?

On the other hand, you could allow arbitrary expressions but evaluate them first, and then label them according to the expression converting into a string. So you wouldn't have to special-case the `factor()` function (or any other function), but people would be able to include arbitrary expressions as long as they used the same expression everywhere.

**Comment by xiaoyingpu** [comment]
This should be taken care of now
